name: 'sfd'

on: push
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Salesforce CLI
        run: |
        
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Auth with the DevHub
        run: 'sfdx auth:jwt:grant --clientid  ${{ secrets.CLIENTID }}  --jwtkeyfile assets/server.key --username  ${{ secrets.USERNAME }}  --setdefaultdevhubusername --setalias my-hub-org'
      - name: Retrive from org
        run: 'sfdx force:source:retrieve -x manifest/package.xml -u  ${{ secrets.USERNAME }}'
      - name: git add
        run: git add .
      - name: Commit files
        run: |
            git config --local user.email "${{ secrets.GIT_EMAIL }}"
            git config --local user.name " ${{ secrets.GIT_USERNAME }}"
            git commit -m "Add changes" -a
      - name: Push changes
        run: git push
      
       
 
        
